//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB_App
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rozmowy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Rozmowy()
        {
            this.Podania = new HashSet<Podania>();
        }
    
        public int idR { get; set; }
        public int idP { get; set; }
        public int idPo { get; set; }
        public Nullable<System.DateTime> dataRozmowy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Podania> Podania { get; set; }
        public virtual Podania Podania1 { get; set; }
        public virtual Pracownicy Pracownicy { get; set; }
    }
}
